run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  varnamelen:
    ignore-names:
      - ok
      - err
      - tC

linters:
  enable-all: true
  disable:
    - ireturn
    - ifshort
    - exhaustivestruct
    - testpackage
    - errchkjson
    - gomnd
    - gci
    - gofumpt
    - paralleltest
    - tagliatelle
  fast: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - funlen
  fix: true
